version: '3'
networks:
  development: null
volumes:
  dbdata: null
  gem_cache: null
  shared_data: null
services:
  keystrings_db:
    image: postgres:latest
    container_name: keystrings_db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: [ 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    environment:
      RAILS_ENV: development
    depends_on:
      - keystrings_db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - shared_data:/var/shared
    networks:
      - development
